parallel sources downloading; ccache
git-svn-id: https://svn.radix.pro/svn/toolchains/trunk@100 0df74aab-45ad-4799-93a1-122938110d35

diff --git a/sources/GNU/EGLIBC/2.12.1/Makefile b/sources/GNU/EGLIBC/2.12.1/Makefile
--- a/sources/GNU/EGLIBC/2.12.1/Makefile
+++ b/sources/GNU/EGLIBC/2.12.1/Makefile
@@ -15,8 +15,12 @@ tarballs   += $(addsuffix .tar.bz2, $(addprefix eglibc-ports-, $(versions)))
 
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
+patches     = $(CURDIR)/patches/eglibc-2.12.1-i18n.patch
 
-BUILD_TARGETS = $(tarballs) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(tarballs) $(sha1s) $(patches)
 
 
 include ../../../../build-system/core.mk
@@ -26,26 +30,28 @@ include ../../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-eglibc-2.12.1-i18n-patch && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-eglibc-2.12.1-i18n-patch ;     ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 downloads_clean:
-	@rm -f $(tarballs) $(sha1s)
-	@rm -f ./patches/eglibc-2.12.1-i18n.patch
+	@rm -f $(tarballs) $(sha1s) $(patches)
diff --git a/sources/GNU/binutils/Makefile b/sources/GNU/binutils/Makefile
--- a/sources/GNU/binutils/Makefile
+++ b/sources/GNU/binutils/Makefile
@@ -20,8 +20,18 @@ versions    = 2.16.1a 2.20.1a 2.21.1a 2.22 2.23.2 2.24 2.25
 tarballs    = $(addsuffix .tar.bz2, $(addprefix binutils-, $(versions)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
+patches     = $(CURDIR)/patches/binutils-2.16.1-AVR.patch
+patches    += $(CURDIR)/patches/binutils-2.20.1-mips-opcodes.patch
+patches    += $(CURDIR)/patches/binutils-2.20.1-x86_64-multilib.patch
+patches    += $(CURDIR)/patches/binutils-2.21.1-x86_64-multilib.patch
+patches    += $(CURDIR)/patches/binutils-2.22-x86_64-multilib.patch
+patches    += $(CURDIR)/patches/binutils-2.23.2-x86_64-multilib.patch
+patches    += $(CURDIR)/patches/binutils-2.24-x86_64-multilib.patch
 
-BUILD_TARGETS = $(tarballs) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(tarballs) $(sha1s) $(patches)
 
 
 include ../../../build-system/core.mk
@@ -31,38 +41,34 @@ include ../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-patch-2.16.1-AVR && ./create.patch.sh )
-	@( cd create-patch-2.20.1-mips-opcodes && ./create.patch.sh )
-	@( cd create-patch-2.20.1-x86_64-multilib && ./create.patch.sh )
-	@( cd create-patch-2.21.1-x86_64-multilib && ./create.patch.sh )
-	@( cd create-patch-2.22-x86_64-multilib && ./create.patch.sh )
-	@( cd create-patch-2.23.2-x86_64-multilib && ./create.patch.sh )
-	@( cd create-patch-2.24-x86_64-multilib && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-patch-2.16.1-AVR             ; ./create.patch.sh ) ; \
+	 ( cd create-patch-2.20.1-mips-opcodes    ; ./create.patch.sh ) ; \
+	 ( cd create-patch-2.20.1-x86_64-multilib ; ./create.patch.sh ) ; \
+	 ( cd create-patch-2.21.1-x86_64-multilib ; ./create.patch.sh ) ; \
+	 ( cd create-patch-2.22-x86_64-multilib   ; ./create.patch.sh ) ; \
+	 ( cd create-patch-2.23.2-x86_64-multilib ; ./create.patch.sh ) ; \
+	 ( cd create-patch-2.24-x86_64-multilib   ; ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 downloads_clean:
-	@rm -f $(tarballs) $(sha1s)
-	@rm -f ./patches/binutils-2.16.1-AVR.patch
-	@rm -f ./patches/binutils-2.20.1-mips-opcodes.patch
-	@rm -f ./patches/binutils-2.20.1-x86_64-multilib.patch
-	@rm -f ./patches/binutils-2.21.1-x86_64-multilib.patch
-	@rm -f ./patches/binutils-2.22-x86_64-multilib.patch
-	@rm -f ./patches/binutils-2.23.2-x86_64-multilib.patch
-	@rm -f ./patches/binutils-2.24-x86_64-multilib.patch
+	@rm -f $(tarballs) $(sha1s) $(patches)
diff --git a/sources/GNU/gcc/gcc-4.9.2/Makefile b/sources/GNU/gcc/gcc-4.9.2/Makefile
--- a/sources/GNU/gcc/gcc-4.9.2/Makefile
+++ b/sources/GNU/gcc/gcc-4.9.2/Makefile
@@ -20,8 +20,18 @@ version     = 4.9.2
 tarballs    = $(addsuffix .tar.bz2, $(addprefix gcc-, $(version)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
+patches     = $(CURDIR)/../patches/gcc-4.9.2-at91sam7s-newlib.patch
+patches    += $(CURDIR)/../patches/gcc-4.9.2-dm644x-newlib.patch
+patches    += $(CURDIR)/../patches/gcc-4.9.2-a1x-newlib.patch
+patches    += $(CURDIR)/../patches/gcc-4.9.2-a2x-newlib.patch
+patches    += $(CURDIR)/../patches/gcc-4.9.2-lpc17xx-multilib.patch
+patches    += $(CURDIR)/../patches/gcc-4.9.2-x86_64-multilib.patch
+patches    += $(CURDIR)/../patches/gcc-4.9.2-bcm74x-libgo.patch
 
-BUILD_TARGETS = $(tarballs) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(tarballs) $(sha1s) $(patches)
 
 
 include ../../../../build-system/core.mk
@@ -31,38 +41,34 @@ include ../../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-patch-4.9.2-at91sam7s-newlib && ./create.patch.sh )
-	@( cd create-patch-4.9.2-dm644x-newlib && ./create.patch.sh )
-	@( cd create-patch-4.9.2-a1x-newlib && ./create.patch.sh )
-	@( cd create-patch-4.9.2-a2x-newlib && ./create.patch.sh )
-	@( cd create-patch-4.9.2-lpc17xx-multilib && ./create.patch.sh )
-	@( cd create-patch-4.9.2-x86_64-multilib && ./create.patch.sh )
-	@( cd create-patch-4.9.2-bcm74x-libgo && ./create.patch.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-patch-4.9.2-at91sam7s-newlib ; ./create.patch.sh ) ; \
+	 ( cd create-patch-4.9.2-dm644x-newlib    ; ./create.patch.sh ) ; \
+	 ( cd create-patch-4.9.2-a1x-newlib       ; ./create.patch.sh ) ; \
+	 ( cd create-patch-4.9.2-a2x-newlib       ; ./create.patch.sh ) ; \
+	 ( cd create-patch-4.9.2-lpc17xx-multilib ; ./create.patch.sh ) ; \
+	 ( cd create-patch-4.9.2-x86_64-multilib  ; ./create.patch.sh ) ; \
+	 ( cd create-patch-4.9.2-bcm74x-libgo     ; ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 downloads_clean:
-	@rm -f $(tarballs) $(sha1s)
-	@rm -f ../patches/gcc-4.9.2-at91sam7s-newlib.patch
-	@rm -f ../patches/gcc-4.9.2-dm644x-newlib.patch
-	@rm -f ../patches/gcc-4.9.2-a1x-newlib.patch
-	@rm -f ../patches/gcc-4.9.2-a2x-newlib.patch
-	@rm -f ../patches/gcc-4.9.2-lpc17xx-multilib.patch
-	@rm -f ../patches/gcc-4.9.2-x86_64-multilib.patch
-	@rm -f ../patches/gcc-4.9.2-bcm74x-libgo.patch
+	@rm -f $(tarballs) $(sha1s) $(patches)
diff --git a/sources/GNU/mpc/Makefile b/sources/GNU/mpc/Makefile
--- a/sources/GNU/mpc/Makefile
+++ b/sources/GNU/mpc/Makefile
@@ -31,23 +31,23 @@ include ../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.gz.sha1sum : %.tar.gz
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
 
 downloads_clean:
 	@rm -f $(tarballs) $(sha1s)
diff --git a/sources/Linux/sunxi/sunxi-3.4/Makefile b/sources/Linux/sunxi/sunxi-3.4/Makefile
--- a/sources/Linux/sunxi/sunxi-3.4/Makefile
+++ b/sources/Linux/sunxi/sunxi-3.4/Makefile
@@ -30,32 +30,33 @@ include ../../../../build-system/core.mk
 
 
 $(description):
-	wget $(WGET_OPTIONS) -N $(url)/$(description)
+	@echo -e "\n======= Downloading $(description) file =======" ; \
+	 echo "$(url)/$(description)" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs ======="
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(defconfigs):
-	@echo -e "\n======= Downloading default config files ======="
-	@for defconfig in $(defconfigs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$defconfig ; \
-	done
+$(defconfigs): $(tarballs)
+	@echo -e "\n======= Downloading default config files =======" ; \
+	 for defconfig in $(defconfigs) ; do \
+	  echo "$(url)/$$defconfig" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
 
 downloads_clean:
 	@rm -f $(description) $(tarballs) $(defconfigs) $(sha1s)
diff --git a/sources/newlib/Makefile b/sources/newlib/Makefile
--- a/sources/newlib/Makefile
+++ b/sources/newlib/Makefile
@@ -22,8 +22,15 @@ versions    = 1.14.0 1.18.0 1.20.0
 tarballs    = $(addsuffix .tar.gz, $(addprefix newlib-, $(versions)))
 sha1s       = $(addsuffix .sha1sum, $(tarballs))
 
+patches     = $(CURDIR)/create-newlib-1.18.0-pkg/newlib-1.18.0-arm-cross.patch
+patches    += $(CURDIR)/create-newlib-1.20.0-pkg/newlib-1.20.0-arm-cross.patch
+packages    = $(CURDIR)/newlib-1.18.0-arm-cross.tar.gz
+packages   += $(CURDIR)/newlib-1.20.0-arm-cross.tar.gz
 
-BUILD_TARGETS = $(tarballs) $(sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS = $(tarballs) $(sha1s) $(patches)
 
 
 include ../../build-system/core.mk
@@ -33,27 +40,29 @@ include ../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs ======="
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@( cd create-newlib-1.18.0-pkg && ./create.pkg.sh )
-	@( cd create-newlib-1.20.0-pkg && ./create.pkg.sh )
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.gz.sha1sum : %.tar.gz
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-newlib-1.18.0-pkg ; ./create.pkg.sh ) ; \
+	 ( cd create-newlib-1.20.0-pkg ; ./create.pkg.sh ) ; \
+	 echo -e "\n"
 
 downloads_clean:
-	@rm -f $(tarballs) $(sha1s)
-	@rm -f newlib-1.18.0-arm-cross.tar.gz ./create-newlib-1.18.0-pkg/newlib-1.18.0-arm-cross.patch
-	@rm -f newlib-1.20.0-arm-cross.tar.gz ./create-newlib-1.20.0-pkg/newlib-1.20.0-arm-cross.patch
+	@rm -f $(tarballs) $(sha1s) $(patches) $(packages)
diff --git a/sources/uClinux/uClibc/Makefile b/sources/uClinux/uClibc/Makefile
--- a/sources/uClinux/uClibc/Makefile
+++ b/sources/uClinux/uClibc/Makefile
@@ -22,8 +22,15 @@ sha1s             = $(addsuffix .sha1sum, $(tarballs))
 locale_tarballs   = $(addsuffix .tgz, $(addprefix uClibc-locale-, $(locale_versions)))
 locale_sha1s      = $(addsuffix .sha1sum, $(locale_tarballs))
 
+patches     = $(CURDIR)/patches/uClibc-0.9.33.2-pth-spinlock.patch
+patches    += $(CURDIR)/patches/uClibc-0.9.33.2-out-of-tree.patch
+patches    += $(CURDIR)/patches/uClibc-0.9.33.2-locale.patch
+patches    += $(CURDIR)/patches/uClibc-0.9.33.2-reduce-execvp-env.patch
 
-BUILD_TARGETS     = $(tarballs) $(locale_tarballs) $(sha1s) $(locale_sha1s)
+.NOTPARALLEL: $(patches)
+
+
+BUILD_TARGETS     = $(tarballs) $(locale_tarballs) $(sha1s) $(locale_sha1s) $(patches)
 
 
 include ../../../build-system/core.mk
@@ -33,51 +40,50 @@ include ../../../build-system/core.mk
 
 
 $(tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
+	@echo -e "\n======= Downloading source tarballs =======" ; \
+	 for tarball in $(tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
 $(locale_tarballs):
-	@echo -e "\n======= Downloading source tarballs =======\n"
-	@for tarball in $(locale_tarballs) ; do \
-	  wget $(WGET_OPTIONS) -N $(url)/$$tarball ; \
-	done
-	@echo -e "\n======= Create Patches =======\n"
-	@( cd create-patch-0.9.33.2-pth-spinlock && ./create.patch.sh )
-	@( cd create-patch-0.9.33.2-out-of-tree && ./create.patch.sh )
-	@( cd create-patch-0.9.33.2-030818-locale && ./create.patch.sh )
-	@( cd create-patch-0.9.33.2-reduce-execvp-env && ./create.patch.sh )
+	@echo -e "\n======= Downloading locale tarballs =======" ; \
+	 for tarball in $(locale_tarballs) ; do \
+	   echo "$(url)/$$tarball" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & \
+	 done ; wait
 
-$(sha1s): %.tar.bz2.sha1sum : %.tar.bz2
+$(sha1s): $(tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
 
-$(locale_sha1s): %.tgz.sha1sum : %.tgz
+$(locale_sha1s): $(locale_tarballs)
 	@for sha in $@ ; do \
-	  echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
-	  wget $(WGET_OPTIONS) -N $(url)/$$sha ; \
-	  touch $$sha ; \
-	  echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
-	  sha1sum --check $$sha ; ret="$$?" ; \
-	  if [ "$$ret" == "1" ]; then \
-	    echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
-	    exit 1 ; \
-	  fi ; \
-	done
+	   echo -e "\n======= Downloading '$$sha' signature =======\n" ; \
+	   echo "$(url)/$$sha" | xargs -n 1 -P 100 wget $(WGET_OPTIONS) -i & wait %1 ; \
+	   touch $$sha ; \
+	   echo -e "\n======= Check the '$$sha' sha1sum =======\n" ; \
+	   sha1sum --check $$sha ; ret="$$?" ; \
+	   if [ "$$ret" == "1" ]; then \
+	     echo -e "\n======= ERROR: Bad '$$sha' sha1sum =======\n" ; \
+	     exit 1 ; \
+	   fi ; \
+	 done
+
+$(patches): $(sha1s) $(locale_sha1s)
+	@echo -e "\n======= Create Patches =======\n" ; \
+	 ( cd create-patch-0.9.33.2-pth-spinlock      ; ./create.patch.sh ) ; \
+	 ( cd create-patch-0.9.33.2-out-of-tree       ; ./create.patch.sh ) ; \
+	 ( cd create-patch-0.9.33.2-030818-locale     ; ./create.patch.sh ) ; \
+	 ( cd create-patch-0.9.33.2-reduce-execvp-env ; ./create.patch.sh ) ; \
+	 echo -e "\n"
 
 downloads_clean:
-	@rm -f $(tarballs) $(locale_tarballs) $(sha1s) $(locale_sha1s)
-	@rm -f ./patches/uClibc-0.9.33.2-pth-spinlock.patch
-	@rm -f ./patches/uClibc-0.9.33.2-out-of-tree.patch
-	@rm -f ./patches/uClibc-0.9.33.2-locale.patch
-	@rm -f ./patches/uClibc-0.9.33.2-reduce-execvp-env.patch
+	@rm -f $(tarballs) $(locale_tarballs) $(sha1s) $(locale_sha1s) $(patches)
